project:
  type: website
  output-dir: docs

website:
  title: "STATSPOLITOLOGEN"
  navbar:
    right:
      - analyser.qmd
      - data.qmd
      - projektet.qmd
      - text: Kontakt
        href: kontakt.qmd

  page-footer:
    center: © Statspolitologen | [Kontakt](/kontakt.qmd)

format:
  html:
    theme: cosmo
    css: styles.css
    mainfont: Roboto